
import Layout from "@/components/layout/Layout";
export const metadata = {
    title: "Polor - Next.js Template",
    description: "Generated by create next app",
};
export default function Home() {
    return (
        <div>
            <Layout>
            </Layout>
        </div>
    );
}
