
import Headers from "@/app/components/headers/header-1";
export const metadata = {
    title: "Polor - Next.js Template",
    description: "Generated by create next app",
};
export default function Home() {
    return (
        <div >
            <Headers />
            <main>
          
            </main>
        </div>
    );
}
